### PR TITLE
quick fix for failures in code actions

### LINKED ISSUE #115: Code actions failures
#113 Has introduced a lot of error responses from the server that seem to be happening on codeAction requests (see note from @rgrinberg in the discussion).

### PR DESCRIPTION
**Pull request by giltho**
fixes #115

### CODE REVIEW

File: ocaml-lsp-server/src/ocaml_lsp_server.ml [hunk 1]
```diff
@@ -175,6 +175,9 @@ let code_action store (params : Lsp.CodeAction.Params.t) =
             (code_action_of_case_analysis params.textDocument.uri res)
         ]
       with
+      | Failure _
+      (* TODO: find a better way of catching this, this is a bit dirty *)
+      | Invalid_argument _
```
Comment (rgrinberg) [inline ocaml-lsp-server/src/ocaml_lsp_server.ml]: I would prefer if you just changed our vendored copy of merlin to raise a new exception. Invalid_argument can be raised by quite a few different calls, so it's too dangerous to catch it here.

Comment (giltho) [reply ocaml-lsp-server/src/ocaml_lsp_server.ml]: That is better indeed ! 
What's the workflow there ? Should I submit a PR to the merlin repo first ?

Comment (rgrinberg) [reply ocaml-lsp-server/src/ocaml_lsp_server.ml]: Submit a PR to my fork: https://github.com/rgrinberg/merlin/tree/remove-lsp

Submitting upstream is also good if you think your solution is good enough. I usually rebase that branch from time to time periodically.
